In [ ]:
pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 31.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 kB 30.1 MB/s eta 0:00:00


In [ ]:
pip install kss

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.7/77.7 kB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.3/131.3 kB 7.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.4/26.4 MB 28.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for kss: filename=kss-4.5.1-py3-none-any.whl size=53220 sha256=b7cadd1f6f42f90f4069b90a46f4c8a9a8a9395c38c2282b3cf703ad8ad279b2
  Stored in directory: /root/.cache/pip/wheels/2f/23/d1/e9c8f5f2e8a61bb4cb8e4fdd0d0c951dab78882e3807c7f7ca
  Created wheel for pecab: filename=pecab-1.0.8-py3-none-any.whl size=26646666 sha256=45f76015715d05d6232b1dfbe48b15090dd31368409adccdbf47a658b4707b13
  Stored in directory: /root/.cache/pip/wheels/5c/91/bf/14eed6eafd0a83f76eab5cf8eb50ddc0b037f059eec2bd2e4a
Successfully built kss pecab


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import nltk
import konlpy

In [ ]:
nltk.download('treebank')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package treebank to /root/nltk_data...
[nltk_data]   Unzipping corpora/treebank.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

## Tokenization

주어진 corpus에서 token이라 불리는 단위로 나누는 작업

Token으로 나누는 방식은 tokenizer마다 조금씩 차이가 있을 수 있음.

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.tokenize import WordPunctTokenizer
from tensorflow.keras.preprocessing.text import text_to_word_sequence

영어에서 Don't와 같이 apostrophe가 들어간 단어를 tokenize하는 방법은 다양함.
각 tokenizer들이 해당 경우를 어떻게 tokenize하는지 살펴보기

In [ ]:
print('word_tokize :', word_tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery  goes for a pastry shop."))

word_tokize : ['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [ ]:
print("WordPunctTokenizer :", WordPunctTokenizer().tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery  goes for a pastry shop."))

WordPunctTokenizer : ['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [ ]:
print("text_to_word_sequence :", text_to_word_sequence("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery  goes for a pastry shop."))

text_to_word_sequence : ["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


각 tokenizer마다 "don't" 라는 단어를 tokenize하는 방법이 모두 다른 걸 확인할 수 있음.

word_tokenize는 "Don't"를 "Do", "n't"로 쪼갰고, WordPunctTokenizer는 "Don", "'", "t"로 쪼갰고, text_word_sequence는 "don't"로 그대로 보존하되, 모든 글자를 소문자로 바꿨음.

### 고려 사항

1. Punctuation을 전부 없애는 건 안된다. Ph.d 와 같은 단어는 "."이 꼭 필요하다. 
2. Apostrophe는 줄임말의 역할을 하는 경우가 있으므로, 이를 고려해야 함.
3. 공백을 함부로 다 없애면 안됨. 공백을 포함해서 한 단어가 되는 경우가 존재함. ex) Rock 'n' Roll

각 tokenizer는 저마다 규칙을 가지고 있음.

아래의 예시는 Penn Treebank Tokenizer이고 다음과 같은 규칙을 따라서 tokenize한다

1. hyphen(-)으로 구성된 단어는 하나로 유지
2. apostrophe로 접어가 함께하는 경우는 분리시킨다. ex) doesn't => "does" "n't"

In [ ]:
from nltk.tokenize import TreebankWordTokenizer

tokenizer = TreebankWordTokenizer()

text = "Starting a home-based restaurant may be an ideal. it doesn't have a food chain or restaurant of their own."
print(tokenizer.tokenize(text))

['Starting', 'a', 'home-based', 'restaurant', 'may', 'be', 'an', 'ideal.', 'it', 'does', "n't", 'have', 'a', 'food', 'chain', 'or', 'restaurant', 'of', 'their', 'own', '.']


### Token의 단위가 단어가 아니라 문장일 경우

Period로 끝나는게 항상 문장의 끝이라고 볼 수는 없다.

In [ ]:
from nltk.tokenize import sent_tokenize

text = "His barber kept his word. But keeping such a huge secret to himself was driving him crazy. Finally, the barber went up a mountain and almost to the edge of a cliff. He dug a hole in the midst of some reeds. He looked about, to make sure no one was near."
print('문장 토큰화1 :',sent_tokenize(text))

문장 토큰화1 : ['His barber kept his word.', 'But keeping such a huge secret to himself was driving him crazy.', 'Finally, the barber went up a mountain and almost to the edge of a cliff.', 'He dug a hole in the midst of some reeds.', 'He looked about, to make sure no one was near.']


문장에 다수의 period가 있어도 성공적으로 문장을 분리함

In [ ]:
text = "I am actively looking for Ph.D. students. and you are a Ph.D student."
print('문장 토큰화2 :',sent_tokenize(text))

문장 토큰화2 : ['I am actively looking for Ph.D. students.', 'and you are a Ph.D student.']


In [ ]:
import kss

text = '딥 러닝 자연어 처리가 재미있기는 합니다. 그런데 문제는 영어보다 한국어로 할 때 너무 어렵습니다. 이제 해보면 알걸요?'
print('한국어 문장 토큰화 :',kss.split_sentences(text))

한국어 문장 토큰화 : ['딥 러닝 자연어 처리가 재미있기는 합니다.', '그런데 문제는 영어보다 한국어로 할 때 너무 어렵습니다.', '이제 해보면 알걸요?']


한글은 tokenize 하기 쉽지 않음

영어와 달리 교착어이기 때문에 원형에 무언가 달라붙어서 단어의 형태가 변하는 경우가 상당히 많음.

형태소 단위로 분리해야함

동음이의어에 대비해서 token들에 품사를 tagging할 수 있음

우선 영어:

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag

text = "I am actively looking for Ph.D. students. and you are a Ph.D. student."
tokenized_sentence = word_tokenize(text)

print('단어 토큰화 :',tokenized_sentence)
print('품사 태깅 :',pos_tag(tokenized_sentence))

단어 토큰화 : ['I', 'am', 'actively', 'looking', 'for', 'Ph.D.', 'students', '.', 'and', 'you', 'are', 'a', 'Ph.D.', 'student', '.']
품사 태깅 : [('I', 'PRP'), ('am', 'VBP'), ('actively', 'RB'), ('looking', 'VBG'), ('for', 'IN'), ('Ph.D.', 'NNP'), ('students', 'NNS'), ('.', '.'), ('and', 'CC'), ('you', 'PRP'), ('are', 'VBP'), ('a', 'DT'), ('Ph.D.', 'NNP'), ('student', 'NN'), ('.', '.')]


한글:

Okt 형태소 분석기를 사용한 결과:

In [ ]:
from konlpy.tag import Okt
from konlpy.tag import Kkma

okt = Okt()
kkma = Kkma()

print('OKT 형태소 분석 :',okt.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('OKT 품사 태깅 :',okt.pos("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('OKT 명사 추출 :',okt.nouns("열심히 코딩한 당신, 연휴에는 여행을 가봐요")) 

OKT 형태소 분석 : ['열심히', '코딩', '한', '당신', ',', '연휴', '에는', '여행', '을', '가봐요']
OKT 품사 태깅 : [('열심히', 'Adverb'), ('코딩', 'Noun'), ('한', 'Josa'), ('당신', 'Noun'), (',', 'Punctuation'), ('연휴', 'Noun'), ('에는', 'Josa'), ('여행', 'Noun'), ('을', 'Josa'), ('가봐요', 'Verb')]
OKT 명사 추출 : ['코딩', '당신', '연휴', '여행']


꼬꼬마 형태소 분석기 사용

In [ ]:
print('꼬꼬마 형태소 분석 :',kkma.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('꼬꼬마 품사 태깅 :',kkma.pos("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('꼬꼬마 명사 추출 :',kkma.nouns("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))  

꼬꼬마 형태소 분석 : ['열심히', '코딩', '하', 'ㄴ', '당신', ',', '연휴', '에', '는', '여행', '을', '가보', '아요']
꼬꼬마 품사 태깅 : [('열심히', 'MAG'), ('코딩', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETD'), ('당신', 'NP'), (',', 'SP'), ('연휴', 'NNG'), ('에', 'JKM'), ('는', 'JX'), ('여행', 'NNG'), ('을', 'JKO'), ('가보', 'VV'), ('아요', 'EFN')]
꼬꼬마 명사 추출 : ['코딩', '당신', '연휴', '여행']


분석기마다 형태소를 분리하는 방법이 다르다. '한'과 '가봐요'에서 차이가 나타난다. Okt는 그대로 tokenize 했지만, 꼬꼬마 분석기는 '하' 'ㄴ', '가보' '아요' 로 형태소의 원형이 최대한 드러나도록 분석했다는 걸 알 수 있다.

## Cleaning and Normalization

Cleaning: corpus의 noise를 제거하는 과정. tokenize 전후에 계속 실시해야 하는 것이지만, 완벽하게 정제하는 것은 거의 힘들다. 그래서 보통 합의점을 찾음

Normalization: 같은 단어인데 표현이 다른 경우, 이 단어들을 통합시켜 같은 단어들로 만들어 주는 단계

Normalization
1. 직접 규칙을 정해주는 경우: 예시, US와 USA는 같은 단어이니까 통합한다
2. 대, 소문자 관련: 기본적으로 대문자와 소문자의 차이로 인해 같은 단어가 다르게 tokenize 된 경우, 통합해줄 필요가 있음. 문장의 첫 글자는 항상 대문자여서 발생하는 현상이 잦음. 
**주의** : 대문자 소문자를 반드시 구별해야 하는 경우도 생김 ex) us(우리) US(미국) 

Cleaning: 불필요한 단어들을 제거하는 단계, 불필요하다는 것은 아무 의미 없는 것들 뿐만 아니라 목적에 맞지 않아서 불필요한 경우도 제거함을 뜻함

1. 등장 빈도가 너무 적은 단어
2. 길이가 짧은 단어 (영어의 경우, 단어의 길이가 평균적으로 6개 정도 되기 때문에 길이가 2~3 인 단어들을 버리는 것을 고려해볼 수 있다.) 주의: dog, cat은 3글자이다.

In [ ]:
import re
text = "I was wondering if anyone out there could enlighten me on this car."

shortword = re.compile(r'W*\b\w{1,2}\b')
print(shortword.sub('', text))

 was wondering  anyone out there could enlighten   this car.


Regular Expression을 활용하면, 규칙적으로 나오는 패턴의 문자열들을 제거하기 용이함.

## 표제어 추출 (Lemmatization)

표제어: 기본 사전형 단어, 즉, 사전에 등재된 단어의 원형

정규화 기법 중 하나로 token에서 표제어를 추출하는 방법 ex) am, are, is => be

### 형태소

형태소: 의미를 가진 가장 작은 단위

- 어간(Stem): 단어의 의미를 담고 있는 부분
- 접사(affix): 단어에 추가적인 의마를 주는 부분

형태학적 parsing: 어간과 접사를 분리하는 작업 ex) cats => "cat" + "s"

- 자립(독립)형태소: 자체적으로 의미를 가지며 다른 형태소들과의 결합없이도 사용 가능한 형태소 ex) 명사 (의존명사는 예외)
- 의존 형태소: 다른 형태소와의 결합을 통해서만 사용할 수 있는 형태소 ex) 동사의 어간, 조사

NLTK에서 표제어 추출 방법

In [ ]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

words = ['policy', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']

print('표제어 추출 전 :', words)
print('표제어 추출 후 :', [lemmatizer.lemmatize(word) for word in words])

표제어 추출 전 : ['policy', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
표제어 추출 후 : ['policy', 'organization', 'have', 'going', 'love', 'life', 'fly', 'dy', 'watched', 'ha', 'starting']


몇몇 알 수 없는 단어들은 품사를 같이 알려줘야 한다.

In [ ]:
lemmatizer.lemmatize('dies', 'v')

'die'

In [ ]:
lemmatizer.lemmatize('watched', 'v')

'watch'

In [ ]:
lemmatizer.lemmatize('has', 'v')

'have'

### 어간 추출 (Stemming)

어간 추출은 정해진 규칙을 이용해서 parsing을 진행하기에 결과물을 보면 사전에 없는 단어들이 나타날 수 있다.

일반적으로 표제어 추출보다 빠른 속도로 이루어질 수 있음

In [ ]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

sentence = "This was not the map we found in Billy Bones's chest, but an accurate copy, complete in all things--names and heights and soundings--with the single exception of the red crosses and the written notes."
tokenized_sentence = word_tokenize(sentence)

print('어간 추출 전 :', tokenized_sentence)
print('어간 추출 후 :', [stemmer.stem(word) for word in tokenized_sentence]) 

어간 추출 전 : ['This', 'was', 'not', 'the', 'map', 'we', 'found', 'in', 'Billy', 'Bones', "'s", 'chest', ',', 'but', 'an', 'accurate', 'copy', ',', 'complete', 'in', 'all', 'things', '--', 'names', 'and', 'heights', 'and', 'soundings', '--', 'with', 'the', 'single', 'exception', 'of', 'the', 'red', 'crosses', 'and', 'the', 'written', 'notes', '.']
어간 추출 후 : ['thi', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'billi', 'bone', "'s", 'chest', ',', 'but', 'an', 'accur', 'copi', ',', 'complet', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'except', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.']


Porter 알고리즘은 기본적으로 "-ize", "-ance", "-al" 등의 어미를 삭제하는 규칙을 사용

In [ ]:
words = ['formalize', 'allowance', 'electrical']

print([stemmer.stem(word) for word in words])

['formal', 'allow', 'electr']


Porter Stemmer와 Lancaster Stemmer 비교

In [ ]:
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer

porter_stemmer = PorterStemmer()
lancaster_stemmer = LancasterStemmer()

words = ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
print('어간 추출 전 :', words)
print('포터 스테머의 어간 추출 후:',[porter_stemmer.stem(w) for w in words])
print('랭커스터 스테머의 어간 추출 후:',[lancaster_stemmer.stem(w) for w in words])

어간 추출 전 : ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
포터 스테머의 어간 추출 후: ['polici', 'do', 'organ', 'have', 'go', 'love', 'live', 'fli', 'die', 'watch', 'ha', 'start']
랭커스터 스테머의 어간 추출 후: ['policy', 'doing', 'org', 'hav', 'going', 'lov', 'liv', 'fly', 'die', 'watch', 'has', 'start']


자신의 상황에 맞는 어간 추출기를 사용해야 한다. 위 랭커스터 스테머의 경우, organization => organ으로 추출했는데, 이는 잘못되었을 가능성이 높다.

### 한글의 경우

한글의 특징

- 동사/형용사의 활용: 어간과 어미가 붙어서 사용된다. 어간과 어미가 원형 그대로 붙는 경우를 규칙 활용, 모양이 변하는 경우 불규칙 활용이라고 한다.

### Stopword

분석할 때 그닥 필요없다고 판단되는 단어 token들을 말함. NLTK에 약 100여개 이상의 불용어들이 정의되어 있음음

In [ ]:
from nltk.corpus import stopwords

stop_words_list = stopwords.words('english')
print('불용어 개수 :', len(stop_words_list))
print('불용어 10개 출력 :',stop_words_list[:10])

불용어 개수 : 179
불용어 10개 출력 : ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]


Stopword 제거하기

In [ ]:
example = "Family is not an important thing. It's everything."
stop_words = set(stopwords.words('english'))

word_tokens = word_tokenize(example)

result = []

for word in word_tokens:
    if word not in stop_words:
        result.append(word)

print('불용어 제거 전 :',word_tokens) 
print('불용어 제거 후 :',result)

불용어 제거 전 : ['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
불용어 제거 후 : ['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


한글도 불용어 제거 가능. 사용자가 직접 정의해서 불용어를 제거해보기기

In [ ]:
okt = Okt()

example = "고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든. 예컨데 삼겹살을 구울 때는 중요한 게 있지."
stop_words = "를 아무렇게나 구 우려 고 안 돼 같은 게 구울 때 는"

stop_words = set(stop_words.split(' '))
word_tokens = okt.morphs(example)

result = [word for word in word_tokens if not word in stop_words]

print('불용어 제거 전 :',word_tokens) 
print('불용어 제거 후 :',result)

불용어 제거 전 : ['고기', '를', '아무렇게나', '구', '우려', '고', '하면', '안', '돼', '.', '고기', '라고', '다', '같은', '게', '아니거든', '.', '예컨데', '삼겹살', '을', '구울', '때', '는', '중요한', '게', '있지', '.']
불용어 제거 후 : ['고기', '하면', '.', '고기', '라고', '다', '아니거든', '.', '예컨데', '삼겹살', '을', '중요한', '있지', '.']


한글 불용어 리스트: https://www.ranks.nl/stopwords/korean (보편적 O, 절대적 X)

## Regular Expression (정규표현식)

`.` : 하나의 임의의 문자에 대응

**re.compile()** Python에게 사용하고자 하는 정규표현식을 전달

**search()**  앞서 compile된 걸 주어진 string에서 찾아봄

In [ ]:
import re

r = re.compile("a.c")
r.search("kkk")

In [ ]:
r.search("abc")

<re.Match object; span=(0, 3), match='abc'>

`?` : ?앞에 있는 문자가 있을 수도 있고 없을 수도 있는 string을 매칭함

In [ ]:
r = re.compile("ab?c")
r.search("abc")
r.search("ac")

<re.Match object; span=(0, 2), match='ac'>

In [ ]:
r.search("abbc")

`*` : 바로 앞 문자가 0개 이상인 string을 매칭함함

In [ ]:
r = re.compile("ab*c")

r.search("ac")

<re.Match object; span=(0, 2), match='ac'>

In [ ]:
r.search("abbc")

<re.Match object; span=(0, 4), match='abbc'>

In [ ]:
r.search("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbc")

<re.Match object; span=(0, 45), match='abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbc'>

`+`: 앞 문자가 1개 이상인 string 매칭칭

In [ ]:
r = re.compile("ab+c")
r.search("ac")

In [ ]:
r.search("abc")

<re.Match object; span=(0, 3), match='abc'>

In [ ]:
r.search("abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbc")

<re.Match object; span=(0, 66), match='abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb>

`^`: ^ 뒤에 주어진 문자열로 시작하는 string 매칭칭

In [ ]:
r = re.compile("^ab")

r.search("ac")

In [ ]:
r.search("abc")

<re.Match object; span=(0, 2), match='ab'>

In [ ]:
r.search("abbcfasdcaefe")

<re.Match object; span=(0, 2), match='ab'>

`{숫자}`: 바로 앞문자의 출현 횟수가 주어진 숫자인 경우를 매칭칭

In [ ]:
r = re.compile("ab{2}c")
r.search("abc")

In [ ]:
r.search("abbbc")

In [ ]:
r.search("abbc")

<re.Match object; span=(0, 4), match='abbc'>

`{숫자1,숫자2}` : 바로 앞문자가 숫자1 이상, 숫자2 이하만큼 반복함 띄어쓰기를 하지 않도록 주의

In [ ]:
r = re.compile("ab{2,8}c")

r.search("ac")

In [ ]:
r.search("abbc")

<re.Match object; span=(0, 4), match='abbc'>

In [ ]:
r.search("abbbbbbbc")

<re.Match object; span=(0, 9), match='abbbbbbbc'>

In [ ]:
r.search("abbbbbc")

<re.Match object; span=(0, 7), match='abbbbbc'>

`{숫자,}`, 주어진 숫자 이상으로 반복되는 string 매칭

In [ ]:
r = re.compile("ab{3,}c")

r.search("abbbc")

<re.Match object; span=(0, 5), match='abbbc'>

In [ ]:
r.search("abbc")

`[]` [] 안에 있는 문자들 중 하나와 매칭, 주어진 문자가 들어가 있는 string이라면 매칭해줌. 범위로 표현 가능 ex) [a-z]: 소문자 전체, [A-Z]: 대문자 전체, [0-9]: 숫자 전체

In [ ]:
r = re.compile("[abc]")
r.search("zzz")

In [ ]:
r.search("a")

<re.Match object; span=(0, 1), match='a'>

In [ ]:
r.search("abc")

<re.Match object; span=(0, 1), match='a'>

In [ ]:
r.search("vgrthtrrefbddee")

<re.Match object; span=(10, 11), match='b'>

In [ ]:
r = re.compile("[a-z]")

r.search("BDFBFE")

In [ ]:
r.search("fdasfdFDSFfsdASDF")

<re.Match object; span=(0, 1), match='f'>

`[^]`: [^] 안에 있는 걸 제외한 모든 문자들을 매칭. 마찬가지로 범위 지정가능능

In [ ]:
r = re.compile("[^abc]")

r.search("abc")

In [ ]:
r.search("abccacb")

In [ ]:
r.search("abcabacabbcacbaacbfabcab")

<re.Match object; span=(18, 19), match='f'>

`re.search()` vs `re.match()`

- `re.search()`: string을 전부 읽어서 해당 패턴이 있으면 가장 처음으로 나온 걸 가져온다
- `re.match()`: string의 맨 첫 부분이 매칭되는지만 확인한다다

In [ ]:
r = re.compile("ab.")

r.match("kkkabc")

In [ ]:
r.search("kkkabc")

<re.Match object; span=(3, 6), match='abc'>

In [ ]:
r.match("abkkkkk")

<re.Match object; span=(0, 3), match='abk'>

`re.split()`, 입력된 정규 표현식을 기준으로 주어진 string을 쪼개서 list로 return 함함

In [ ]:
text = "eins zwei drei vier"
re.split(" ", text)

['eins', 'zwei', 'drei', 'vier']

In [ ]:
text = """eins
zwei
drei
vier
fuenf"""

re.split("\n", text)

['eins', 'zwei', 'drei', 'vier', 'fuenf']

In [ ]:
text = "사과+딸기+수박+메론+바나나"

re.split("\+", text)

['사과', '딸기', '수박', '메론', '바나나']

`re.findall()`, 매칭되는 모든 결과를 list에 담아서 return

In [ ]:
text = """이름 : 김철수
전화번호 : 010 - 1234 - 1234
나이 : 30
성별 : 남"""

re.findall("\d+", text)

['010', '1234', '1234', '30']

`re.sub()`, 주어진 정규식과 매칭되는 모든 문자열들을 대체할 수 있음

In [ ]:
text = "Regular expression : A regular expression, regex or regexp[1] (sometimes called a rational expression)[2][3] is, in theoretical computer science and formal language theory, a sequence of characters that define a search pattern."

preprocessed_text = re.sub('[^a-zA-Z]', ' ', text) # 알파벳 이외의 모든 문자는 공백으로 대체
print(preprocessed_text)

Regular expression   A regular expression  regex or regexp     sometimes called a rational expression        is  in theoretical computer science and formal language theory  a sequence of characters that define a search pattern 


### Tokenize Using Regular Expression


In [ ]:
from nltk.tokenize import RegexpTokenizer

text = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop"

tokenizer1 = RegexpTokenizer("[\w]+")
tokenizer2 = RegexpTokenizer("\s+", gaps=True)

print(tokenizer1.tokenize(text))
print(tokenizer2.tokenize(text))

['Don', 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'Mr', 'Jone', 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']
["Don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name,', 'Mr.', "Jone's", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


## Integer Encoding

단어들을 숫자로 바꾸는 것이 컴퓨터 입장에서는 훨씬 다루기 편하기 때문에 단어들을 각각 고유한 숫자로 mapping해주는 과정이 필요 => encoding

1. 단어의 빈도수를 이용한 encoding:

In [ ]:
raw_text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

In [ ]:
sentences = sent_tokenize(raw_text)
print(sentences)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [ ]:
vocab = {}
preprocessed_sentences = []
stop_words = set(stopwords.words('english'))

for sentence in sentences:
    tokenized_sentence = word_tokenize(sentence)
    result = []

    for word in tokenized_sentence:
        word = word.lower()
        if word not in stop_words:  # stopword가 아니어야 한다
            if len(word) > 2:  # 길이가 3 이상인 단어만 받는다
                result.append(word)
                if word not in vocab:
                    vocab[word] = 0
                vocab[word] += 1
    preprocessed_sentences.append(result)
print(preprocessed_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [ ]:
all_words_list = sum(preprocessed_sentences, [])
print(all_words_list)

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


In [ ]:
from collections import Counter

In [ ]:
vocab = Counter(all_words_list)
print(vocab)

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})


In [ ]:
vocab_size = 5
vocab = vocab.most_common(vocab_size) # 상위 5개
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [ ]:
word_to_index = {}
# 빈도수가 높을수록 더 낮은 index 부여
i = 0
for (word, frequency) in vocab:
    i = i + 1
    word_to_index[word] = i

print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


NLTK의 FreqDist도 Counter처럼 사용 가능능

In [ ]:
from nltk import FreqDist
import numpy as np

In [ ]:
vocab = FreqDist(np.hstack(preprocessed_sentences))

In [ ]:
vocab = vocab.most_common(vocab_size)

In [ ]:
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [ ]:
word_to_index = {word[0] : index + 1 for index, word in enumerate(vocab)}
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


### Keras에서 Text Preprocessing

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts(preprocessed_sentences)
print(tokenizer.word_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}


빈도수에 따라서 index가 부여된 걸 확인할 수 있음

In [ ]:
print(tokenizer.word_counts)

OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])


주어진 단어의 encoding을 이용해서 텍스트를 정수로 바꿔주기

In [ ]:
print(tokenizer.texts_to_sequences(preprocessed_sentences))

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


아까처럼 상위 5개의 단어만 사용하겠다고 하면:

In [ ]:
tokenizer = Tokenizer(num_words = vocab_size + 1)
tokenizer.fit_on_texts(preprocessed_sentences)

vocab_size + 1 인 이유는 keras가 index를 0부터 시작하기 때문에 5개의 단어를 넣고 싶으면 +1을 해줘야 함. 하지만 실제로 index 0은 결과에 나타나지 않는데, 이는 추후에 나올 padding을 위한 것임.

In [ ]:
print(tokenizer.texts_to_sequences(preprocessed_sentences))

[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


Keras는 상위 5개라고 하면, 그 외의 단어들은 그냥 날려버린다. 이를 방지하기 위해서는 Tokenizer에 `oov_token = 'OOV'`라고 추가해야 한다.

**OOV** 는 단어장에 없는 단어를 지칭하는 말이다.

In [ ]:
tokenizer = Tokenizer(num_words = vocab_size + 1, oov_token = 'OOV')
tokenizer.fit_on_texts(preprocessed_sentences)

In [ ]:
print(tokenizer.texts_to_sequences(preprocessed_sentences))

[[2, 1], [2, 1, 1], [2, 4, 1], [1, 3], [3, 5, 4, 3], [4, 3], [2, 5, 1], [2, 5, 1], [2, 5, 3], [1, 1, 4, 3, 1, 2, 1], [2, 1, 4, 1]]


OOV들은 전부 index 1 에 mapping 되어 있고, 실제 단어는 index 2부터 시작한다.

In [ ]:
print('OOV의 index : {}'.format(tokenizer.word_index['OOV']))

OOV의 index : 1


## Padding

자연어는 길이가 제각각이지만, 기계는 반드시 고정된 길이의 데이터를 요구하기에, 모든 데이터들의 길이를 맞춰주는 작업을 padding이라고 함

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
preprocessed_sentences = [['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

In [ ]:
max_len = max(len(item) for item in encoded)
print('최대 길이 :', max_len)

최대 길이 : 7


최대 길이에 맞춰 다른 문장들도 0으로 채워준다. 이때 0으로 채워주면 zero padding이라고 한다.

In [ ]:
for sentence in encoded:
    while len(sentence) < max_len:
        sentence.append(0)

padded_np = np.array(encoded)
padded_np

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

### Padding with Keras

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [ ]:
padded = pad_sequences(encoded)
padded

array([[ 0,  0,  0,  0,  0,  1,  5],
       [ 0,  0,  0,  0,  1,  8,  5],
       [ 0,  0,  0,  0,  1,  3,  5],
       [ 0,  0,  0,  0,  0,  9,  2],
       [ 0,  0,  0,  2,  4,  3,  2],
       [ 0,  0,  0,  0,  0,  3,  2],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  2],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 0,  0,  0,  1, 12,  3, 13]], dtype=int32)

텍스트 뒤를 padd하고 싶다면 `padding=post`를 추가한다.

In [ ]:
padded = pad_sequences(encoded, padding='post')
padded

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]], dtype=int32)

Padding 할 때, 최대 길이에 맞추는 대신, 특정 길이로 제한하는 것도 가능함함. 

대신 이렇게 하면, 몇몇 sentence들은 일부가 잘려나갈 수 있음.

In [ ]:
padded = pad_sequences(encoded, padding='post', maxlen=5)
padded

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0]], dtype=int32)

잘리는 sentence들 중, 뒤를 잘리게 하고 싶다면 `truncating='post'`를 준다

In [ ]:
padded = pad_sequences(encoded, padding='post', maxlen=5, truncating='post')

In [ ]:
padded

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 7,  7,  3,  2, 10],
       [ 1, 12,  3, 13,  0]], dtype=int32)

때로는 다른 숫자로 padding을 하고 싶을 수도 있으니 그때는 `value`를 적어준다.

In [ ]:
padded = pad_sequences(encoded, padding='post', maxlen=5, value=14)
padded

array([[ 1,  5, 14, 14, 14],
       [ 1,  8,  5, 14, 14],
       [ 1,  3,  5, 14, 14],
       [ 9,  2, 14, 14, 14],
       [ 2,  4,  3,  2, 14],
       [ 3,  2, 14, 14, 14],
       [ 1,  4,  6, 14, 14],
       [ 1,  4,  6, 14, 14],
       [ 1,  4,  2, 14, 14],
       [ 3,  2, 10,  1, 11],
       [ 1, 12,  3, 13, 14]], dtype=int32)

## Vocabulary 단어 집합

단어 집합은 중복을 허용하지 않은 서로 다른 단어들의 집합이다. 이 단어 집합에 고유한 정수를 부여하면 encoding이 완료된다.

## One-Hot Encoding

앞서 단어마다 고유한 정수를 부여했는데, one-hot encoding은 고유한 정수가 아닌 고유한 벡터를 부여한다.전부 0인 벡터에 해당 단어의 고유한 정수에 해당하는 위치에만 1을 넣은 형태의 벡터가 완성된다. 이러한 벡터를 One-Hot Vector라고 함.

In [ ]:
from konlpy.tag import Okt

okt = Okt()
tokens = okt.morphs("나는 자연어 처리를 배운다")
print(tokens)

['나', '는', '자연어', '처리', '를', '배운다']


In [ ]:
word_to_index = {word : index for index, word in enumerate(tokens)}
print('단어 집합 :', word_to_index)

단어 집합 : {'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '배운다': 5}


In [ ]:
def one_hot_encoding(word, word_to_index):
    one_hot_vector = [0]*(len(word_to_index))
    index = word_to_index[word]
    one_hot_vector[index] = 1
    return one_hot_vector

one_hot_encoding("자연어", word_to_index)

[0, 0, 1, 0, 0, 0]

자연어는 index 값이 2 이므로, index 2의 위치에만 1이 저장되어 있는 걸 볼 수 있다.

### One-Hot Encoding in Keras

In [ ]:
text = "나랑 점심 먹으러 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야"

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
print('단어 집합 :', tokenizer.word_index)

단어 집합 : {'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으러': 5, '메뉴는': 6, '최고야': 7}


In [ ]:
sub_text = "점심 먹으러 갈래 메뉴는 햄버거 최고야"
encoded = tokenizer.texts_to_sequences([sub_text])[0]
print(encoded)

[2, 5, 1, 6, 3, 7]


In [ ]:
one_hot = to_categorical(encoded)
print(one_hot)

[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


One-Hot encoding의 단점:
1. 각 단어의 크기가 너무 커진다
2. 단어들 간의 유사도를 나타낼 방법이 없다.

## 데이터 분리

데이터를 학습할 때 처음부터 모든 데이터를 다 주면 안되고, 일부분을 때어내서 그 데이터는 해당 model이 얼마나 잘하는지 test를 하는 걸로 남겨야 합니다.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
X, y = zip(['a', '1'], ['b', '2'], ['c', '3'])
print('X :', X)
print('Y :', y)

X : ('a', 'b', 'c')
Y : ('1', '2', '3')


In [ ]:
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [ ]:
X = df['메일 본문']
y = df['스팸 메일 유무']

In [ ]:
print('X 데이터 :',X.to_list())
print('y 데이터 :',y.to_list())

X 데이터 : ['당신에게 드리는 마지막 혜택!', '내일 뵐 수 있을지 확인 부탁드...', '도연씨. 잘 지내시죠? 오랜만입...', '(광고) AI로 주가를 예측할 수 있다!']
y 데이터 : [1, 0, 0, 1]


In [ ]:
np_array = np.arange(0,16).reshape((4,4))
print('전체 데이터 :')
print(np_array)

전체 데이터 :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
X = np_array[:, :3]
y = np_array[:,3]

print('X 데이터 :')
print(X)
print('y 데이터 :',y)

X 데이터 :
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
y 데이터 : [ 3  7 11 15]


분리하는 방법은 여러가지인 걸 알 수 있다. 주로 dataframe이나 numpy ndarray를 이용해서 indexing을 하면 쉽게 할 수 있다.

Scikit-Learn 으로 Train test set 분리하기

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=1234)

이 방법의 장점은 알아서 주어진 비율대로 섞어준다.

## 한국어 전처리 패키지

### Py-Hanspell

맞춤법 검사기

In [ ]:
pip install git+https://github.com/ssut/py-hanspell.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/ssut/py-hanspell.git to /tmp/pip-req-build-mcu3f68z
  Running command git clone --filter=blob:none --quiet https://github.com/ssut/py-hanspell.git /tmp/pip-req-build-mcu3f68z
  Resolved https://github.com/ssut/py-hanspell.git to commit 8e993cf46f97f9d665c15633a0fc78ac1b727713
  Preparing metadata (setup.py) ... done
  Created wheel for py-hanspell: filename=py_hanspell-1.1-py3-none-any.whl size=4865 sha256=d379af7ed679f4ecd94da9dbef87ba0a34eb871694144371ad86a2a74f8541ab
  Stored in directory: /tmp/pip-ephem-wheel-cache-7gpls012/wheels/2e/43/cc/753c9e1d91affb9ea40e186cea5654fb9231deb454da6724e5
Successfully built py-hanspell


In [ ]:
pip install soynlp

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 416.8/416.8 kB 11.0 MB/s eta 0:00:00
